name: Sergey Kovalev
title: skaska
subtitle: AI-first solutions
logo: "/assets/skaska.png"

email: s.kovalev@inbox.ru
description: >- # this means to ignore newlines until "baseurl:"
  AI passioned and digital twin amazed
  cto, solution architect and team lead
baseurl: ""
url: "https://skaska.pro" 

repository: "sergey-ko/skaskapro"

# Build settings
#theme: minima
#minima:
#  skin: dark

#theme: jekyll-theme-minimal
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
permalink: /:title

plugins:
  - jekyll-feed
  - jekyll-sitemap

search: true  
include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true      

author:
  name: "Sergey Kovalev"
  avatar: "/assets/me.jpg"
  bio: "CTO, Architect" # Note: Markdown is allowed
  #location: "Everywhere"
  links:
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/Sergey0Kovalev"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/skovalev/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/sergeyk0"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCyWIvQK2Ss6W5_5sdSK4mAw"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sergey-ko"
    - label: "Resume"
      icon: "fas fa-fw fa-file"
      url: "assets/Sergey Kovalev 2024.pdf"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-383425PCBK"
    anonymize_ip: false # default

    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
